SkjoLD/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', include('semantic.urls', namespace='semantic')),
    url(r'^semantic/', include('semantic.urls', namespace='semantic-semantic', app_name='semantic')),
    url(r'^thesaurus/', include('thesaurus.urls', namespace='thesaurus-semantic', app_name='thesaurus')),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),
    url(r'^autocomplete/', 'semantic.views.autocomplete'),
)

thesaurus/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', include('haystack.urls'), name='thesaurus_search'),
    url(r'^(?P<uri>00)/$', views.scheme, name='scheme'),
    url(r'^(?P<uri>[0-9]{2})/$', views.collection, name='collection'),
    url(r'^(?P<uri>[0-9]{6})/$', views.collection, name='collection'),
    url(r'^(?P<uri>T?[0-9a-zA-Z]+)/$', views.resource, name='detail'),
]

semantic/models.py
from django.db import models
from django.db.models import Q
from django.db.models.base import ObjectDoesNotExist
from django.conf import settings
from django.utils import translation
from django.core.urlresolvers import reverse

# Create your models here.
class Prefix(models.Model):
    name = models.CharField(max_length=200)
    uri = models.URLField()

    class Meta:
        verbose_name_plural = 'prefixes'

    def __unicode__(self):
        return self.name

    def turtle(self):
        return "@prefix " + self.name + ": <" + self.uri + "> ."

class OwlSuper(models.Model):
    OWL_TYPES = (
        ('owl:Class','Class'),
        ('owl:DatatypeProperty','DatatypeProperty'),
        ('owl:ObjectProperty','ObjectProperty'),
    )
    prefix = models.ForeignKey('Prefix')
    owl_type = models.CharField(max_length=200,choices=OWL_TYPES)
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.prefix.__str__() + ':' + self.name

    def uri(self):
        return self.prefix.uri + '#' + self.name

class Resource(models.Model):
    uri = models.CharField(max_length=200)
    resource_type = models.ForeignKey('OwlSuper', limit_choices_to={'owl_type': 'owl:Class'})
    label_class = models.ForeignKey('OwlSuper', related_name='label_class', limit_choices_to=Q(name__icontains='label') | Q(name__icontains='title'))

    def pref_label(self):
        #Get the preferred label for whatever the current language is
        current_language = translation.get_language()
        try:
            label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class) & Q(property_language=current_language))
        except Property.DoesNotExist:
            try:
                label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class) & Q(property_language=settings.LANGUAGE_CODE))
            except Property.DoesNotExist:
                try:
                    label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class))
                except Property.DoesNotExist:
                    return self.uri
                else:
                    return label.property_text
                #return self.uri
            else:
                return label.property_text
        else:
            return label.property_text

    def pref_label_for(self, language):
        current_language = language
        try:
            label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class) & Q(property_language=current_language))
        except Property.DoesNotExist:
            try:
                label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class) & Q(property_language=settings.LANGUAGE_CODE))
            except Property.DoesNotExist:
                try:
                    label = Property.objects.get(Q(property_source=self) & Q(property_type=self.label_class))
                except Property.DoesNotExist:
                    return self.uri
                else:
                    return label.property_text
                #return self.uri
            else:
                return label.property_text
        else:
            return label.property_text
            
    def __unicode__(self):
        return self.pref_label()

    def get_absolute_url(self):
        return reverse('semantic:detail', kwargs={'uri': self.uri})

    def turtle(self):
        # only return the type declaration; properties and relationships can be done separately
        # a base uri prefix needs to be registered in Prefixes, aliased to _
        return "_:" + self.uri + " a " + self.resource_type.__unicode__()

    def turtle_resolved(self):
        # only gets the preferred labels
        return_str = "_:" + self.uri + " a " + self.resource_type.__unicode__() + "; "
        qs = self.property_set.filter(property_type=self.label_class)
        for p in qs:
            if p == qs.latest('property_language'):
                return_str += p.turtle() + " . "
            else:
                return_str += p.turtle() + " ; "
        return return_str

class Relationship(models.Model):
    relationship_source = models.ForeignKey('Resource')
    relationship_type = models.ForeignKey('OwlSuper', limit_choices_to=Q(owl_type='owl:ObjectProperty') & ~Q(name__icontains='match'))
    relationship_target = models.ForeignKey('Resource', verbose_name='Target Resource', related_name='target_of')

    def __unicode__(self):
        return self.relationship_source.__str__() + ' ' + self.relationship_type.__str__() + ' ' + self.relationship_target.__str__()

    def turtle(self):
        return self.relationship_type.__unicode__() + " _:" + self.relationship_target.uri

    def turtle_resolved(self):
        return_str = ''
        for lang in settings.LANGUAGES:
            return_str += self.relationship_type.__unicode__() + " " + self.relationship_target.pref_label_for(lang) + "\n"
        return return_str

class Property(models.Model):
    property_source = models.ForeignKey('Resource')
    property_text = models.TextField()
    property_language = models.CharField(max_length=2,choices=settings.LANGUAGES)
    property_type = models.ForeignKey('OwlSuper', limit_choices_to={'owl_type': 'owl:DatatypeProperty'})

    class Meta:
        verbose_name_plural = 'properties'
        ordering = ['property_type','property_language','property_text']

    def __unicode__(self):
        return_string = self.property_type.__str__() + ' "' + self.property_text + '"'
        
        if self.property_language:
            return_string += '@' + self.property_language
            
        return return_string

    def turtle(self):
        return self.__unicode__()

class Match(models.Model):
    match_source = models.ForeignKey('Resource')
    match_type = models.ForeignKey('OwlSuper', limit_choices_to=Q(owl_type='owl:ObjectProperty') & Q(name__icontains='match'))
    match_target = models.URLField(null=True, blank=True)
    match_internal_model = models.CharField(max_length=200, null=True, blank=True)
    match_internal_view = models.CharField(max_length=200, null=True, blank=True)
    match_internal_uri = models.CharField(max_length=200, null=True, blank=True)
    resolve_label = models.BooleanField()

    class Meta:
        verbose_name_plural = 'matches'

    def __unicode__(self):
        return self.match_source + ' ' + self.match_type + ' ' + self.match_target

    def internal_scope(self):
        return self.match_internal_model + ':' + self.match_internal_view
    #to do: create a general purpose label resolver that takes in a match target URI and attempts to return an appropriate label
    # This might be better achieved outside the program, however...

thesaurus/models.py
from django.db import models
from django.db.utils import OperationalError, ProgrammingError
import semantic
from semantic.models import Resource, Relationship, Property, Match, OwlSuper, Prefix

# Create your models here.

#Managers for proxy models
class PreferredLabelManager(models.Manager):
    def get_queryset(self):
        return super(PreferredLabelManager, self).get_queryset().filter(
            property_type = OwlSuper.objects.get(name='prefLabel').id
        )

class AlternateLabelManager(models.Manager):
    def get_queryset(self):
        return super(AlternateLabelManager, self).get_queryset().filter(
            property_type = OwlSuper.objects.get(name='altLabel').id
        )

class ScopeNoteManager(models.Manager):
    def get_queryset(self):
        return super(ScopeNoteManager, self).get_queryset().filter(
            property_type = OwlSuper.objects.get(name='scopeNote').id
        )

class ConceptManager(models.Manager):
    def get_queryset(self):
        return super(ConceptManager, self).get_queryset().filter(
            resource_type = OwlSuper.objects.get(name='Concept').id
        )
class CollectionManager(models.Manager):
    def get_queryset(self):
        return super(CollectionManager, self).get_queryset().filter(
            resource_type = OwlSuper.objects.get(name='Collection').id
        )

class ConceptSchemeManager(models.Manager):
    def get_queryset(self):
        return super(ConceptSchemeManager, self).get_queryset().filter(
            resource_type = OwlSuper.objects.get(name='ConceptScheme').id
        )


#Proxy models from semantic.models
class Concept(Resource):
    objects = ConceptManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"
  
    # The following try/except prevents the manage.py script from failing in case
    # migrations have not already succeeded. Since manage.py is how you invoke 
    # the migrations in the first place, it is essential that the script work.
    try:
        res_type = OwlSuper.objects.get(name='Concept').id
    except OperationalError:
        res_type = None
    except OwlSuper.DoesNotExist:
        res_type = None
    except ProgrammingError:
        res_type = None

    def create(cls, resource_type=res_type):
        concept = cls(resource_type=resource_type)
        return concept

    #def get_absolute_url(self):
    #    from django.core.urlresolvers import reverse
        #return reverse('thesaurus:detail', kwargs={'uri': self.uri})
        # below is wrong, but above doesn't work yet...
    #    return "/thesaurus/%i/" % self.uri

class Collection(Resource):
    objects = CollectionManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"

class ConceptScheme(Resource):
    objects = ConceptSchemeManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"

class PreferredLabel(Property):
    objects = PreferredLabelManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"

class AlternateLabel(Property):
    objects = AlternateLabelManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"

class ScopeNote(Property):
    objects = ScopeNoteManager()

    class Meta:
        proxy = True
        app_label = "thesaurus"

thesaurus/views.py
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext, loader
from django.template.context_processors import i18n
from django.utils import translation
from haystack.utils import Highlighter

from .models import Concept
from .models import Collection
from .models import Resource
from .models import OwlSuper
from .models import ConceptScheme

def index(request):
    concept_schemes = ConceptScheme.objects.all
    return render(request, 'thesaurus/index.html', {'concept_schemes': concept_schemes})

def resource(request, uri):
    resource = get_object_or_404(Resource, uri=uri)
    microthesauri = Resource.objects.filter(relationship__relationship_target = resource, relationship__relationship_type = OwlSuper.objects.get(name='member').id)
    return render(request, 'thesaurus/detail.html', {'resource': resource, 'microthesauri': microthesauri, 'uri': uri })

def scheme(request, uri):
    concept_scheme = get_object_or_404(ConceptScheme, uri=uri)
    domains = Collection.objects.filter(uri__regex = r'^\d\d$')
    return render(request, 'thesaurus/scheme.html', {'concept_scheme': concept_scheme, 'domains': domains, 'uri': uri})

def collection(request, uri):
    collection = get_object_or_404(Collection, uri=uri)
    children = collection.relationship_set.filter(relationship_type = OwlSuper.objects.get(name='member').id)
    return render(request, 'thesaurus/collection.html', {'collection': collection, 'children': children, 'uri': uri})

thesaurus/templates/thesaurus/collection.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <h1>{{ collection.pref_label }}</h1>
      <div class="row">
        <div class="col-md-12">
          {% if children %}
          <div class="panel panel-default">
            <div class="panel-heading">Members</div>
              <ul class="list-group">
              {% for child in children.all %}
              <li class="list-group-item">skos:member
                {% if child.relationship_target.resource_type.name = 'Collection' %}
                  <a href="{% url 'thesaurus:collection' child.relationship_target.uri %}">{{ child.relationship_target.pref_label }}</a>
                {% else %}
                  <a href="{% url 'thesaurus:detail' child.relationship_target.uri %}">{{ child.relationship_target.pref_label }}</a>
                {% endif %}
              </li>              
              {% endfor %}
            </ul>
            {% endif %}
          </div><!-- /panel -->
        </div><!-- /col -->
      </div><!-- /row -->
    </div><!-- /row -->
  </div><!-- /container -->
{% endblock %}

thesaurus/templates/thesaurus/detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div class="row">
    <h1>{{ resource.pref_label }}</h1>
    {% for microthesaurus in microthesauri.all %}
    <ul class="breadcrumb">
        <li>{{ microthesaurus.resource_type }}: 
          <a href="{% url 'thesaurus:detail' microthesaurus.uri %}">{{ microthesaurus }}</a>
        </li>
    </ul>
    {% endfor %}
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">Labels and Properties</div>
          <ul class="list-group">
          {% for property in resource.property_set.all %}
            <li class="list-group-item">{{ property }}</li>
          {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">Relationships</div>
          <ul class="list-group">
          {% for relationship in resource.relationship_set.all %}
            <li class="list-group-item">{{ relationship.relationship_type }} 
              <a href="{% url 'thesaurus:detail' relationship.relationship_target.uri %}">{{ relationship.relationship_target }}</a>
            </li>
          {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    {% if resource.match_set %}
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">Matches in other data sets</div>
            <ul class="list-group">
            {% for match in resource.match_set.all %}
              {% if match.match_target %}
                <li class="list-group-item">
                {{ match.match_type }} <a href="{{ match.match_target }}">{{ match.match_target }}</a>
                </li>
              {% else %}
                <li class="list-group-item">
                {{ match.match_type }} <a href="{% url match.internal_scope match.match_internal_uri %}">{{ resource.pref_label }}</a> ({{ match.match_internal_view }})
                </li>
              {% endif %}
            {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}

thesaurus/templates/thesaurus/index.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			<h1>{{ concept_scheme.prefLabel }}</h1>
			<div class="row">
			<div class="col-md-6">
				<ul class="list-group">
					<li class="list-group-item disabled">Properties</li>
					{% for property in concept_scheme.property_set.all %}
						<li class="list-group-item">{{ property }}</li>
					{% endfor %}
				</ul>
			</div>
				<div class="col-md-6">
					{% if domains %}
					<ul class="list-group">
						<li class="list-group-item disabled">Relationships</li>
						{% for domain in domains.all %}
						<li class="list-group-item">{{ domain.resource_type }} 
							<a href="{% url 'thesaurus:detail' domain.uri %}">{{ domain }}</a>
						</li>
								
						{% endfor %}
					</ul>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

thesaurus/templates/thesaurus/scheme.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <h1>{{ concept_scheme.pref_label }}</h1>
      <div class="row">
        <div class="col-md-12">
          {% if domains %}
          <ul class="list-group">
            <li class="list-group-item disabled">Domains</li>
            {% for domain in domains.all %}
            <li class="list-group-item">{{ domain.resource_type }} 
              <a href="{% url 'thesaurus:collection' domain.uri %}">{{ domain }}</a>
            </li>
                
            {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}